### ISSUE TITLE
Usability Testing Preparation: Documentation and IRB

### ISSUE THREAD

**Issue by stephanievaskomsu** [MESH-Research/Pilcrow#1775]
- [x] SEV drafts application form, consent form, recruitment email, and usability testing script

- [x] SEV shares drafts with SB and SS for feedback

- [x] SEV integrates feedback from SB and SS 

- [x] SEV submits application to IRB

UPDATE: this is a quality improvement activity, so no IRB

**Comment by sattler9** [comment]
Shelby and Stephanie have been added to the original IRB. Scheduling for the week of June 14th

**Comment by stephanievaskomsu** [comment]
Above comment incorrect. We can start scheduling for then after 1) instrument goes to IRB and 2) the staging site/seeded articles are ready.
