### ISSUE TITLE
Dependency Licenses

### ISSUE THREAD

**Issue by gmeben** [MESH-Research/Pilcrow#1838]
### Problem/Why
There may be dependencies of Pilcrow that have licenses that require attribution. For example, the free version of the Font Awesome icon library uses [Creative Commons 4.0 Attribution](https://fontawesome.com/license/free). The good news is that Font Awesome considers the default comments embedded within its source code as "sufficient attribution" which requires no further effort on the part of Pilcrow maintainers. However, other dependencies may have less lax attribution requirements as part of their licenses. 

### Goal/What
Audit the licenses of dependencies of Pilcrow. Note which have attribution or other constraints/requirements. Fulfill those requirements when and where necessary. This may involve the creation of a new page on Pilcrow. 

### Solution/How
Read through GitHub's overview on licensing here: https://opensource.guide/legal/

Audit dependencies and note which have requirements that need to be fulfilled. Fulfill requirements. 

### To Do / Acceptance Criteria

- [ ] Audit dependencies for license usages
- [ ] Note which dependencies require attention, like attribution
- [ ] Fulfill license requirements when and where necessary

### Review Checklist

- [ ] All dependencies have their licenses accounted for
